---
title: "Projects"
author: "Colleen Hoskins"
---
## Pyramid Lake Cyanobacterial Blooms
<iframe 
  src="https://csurams.maps.arcgis.com/apps/instant/slider/index.html?appid=62a2d66cf55b47fe8e5f3d93ca5e17db" 
  width="100%" 
  height="600" 
  style="border:none;">
</iframe>
For this project, I used ArcGIS Pro to analyze and visualize cyanobacterial blooms in Pyramid Lake, NV. NDVI was calculated from Landsat 8-9 imagery for four bloom events, and a threshold of 0.25 was applied to identify areas of potential cyanobacterial activity. The slider app above displays a vectorized  representation of NDVI for blooms that occurred on 10/29/2017, 9/22/2021, 10/6/2023 and 10/8/2024.  

View the StoryMap here: [Pyramid Lake Cyanobacterial Blooms](https://storymaps.arcgis.com/stories/2c2f03375fc8477d94bd3c72ec287b1a)

## Trout Creek Watershed Analysis
<iframe src="trout_creek_map.html" width="100%" height="600px" style="border:none;"></iframe>

This project examines the hydrology of the Trout Creek watershed, located on the southern side of Lake Tahoe, CA for water years 1960-2023. Using datasets from USGS and climateengine.org, I analyzed water budget components including precipitation, evapotranspiration, snow water equivalent, and soil moisture. The analysis compares pre- and post-restoration periods of the watershed, with results visualized using the R packages `ggplot2`, `tmap`, and `plotly`. 

View the project here: [Trout Creek Watershed Analysis](watershed_analysis.qmd)
